#
services:
  postgres:
    image: pgvector/pgvector:pg18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/setup-pgvector.sh:/docker-entrypoint-initdb.d/setup-pgvector.sh

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP server
