GET http://localhost:3000/health

###

POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "username": "kucingkode",
  "email": "fazle@adyuta.group",
  "password": "StrongPassword123"
}