export const ERROR_HTTP_STATUS_CODES: {
  [key: string]: number;
} = {
  // domain
  EMAIL_TAKEN: 409,
  USERNAME_TAKEN: 409,
  INCORRECT_PASSWORD: 401,
  INCORRECT_CREDENTIALS: 401,
  NO_PASSWORD_SET: 409,

  // commons
  VALIDATION_ERROR: 400,
  UNAUTHORIZED: 401,
  INTERNAL_ERROR: 500,
};
