export const ERROR_HTTP_STATUS_CODES: {
  [key: string]: number;
} = {
  ALREADY_EXISTS: 409,
  EMAIl_NOT_VERIFIED: 403,
  EMAIL_TAKEN: 409,
  INCORRECT_PASSWORD: 401,
  INCORRECT_CREDENTIALS: 401,
  NO_PASSWORD_SET: 409,
  NOT_FOUND: 404,
  SERVICE_UNAVAILABLE: 503,
  UNAUTHORIZED: 401,
  USERNAME_TAKEN: 409,

  POST_ALREADY_LIKED: 409,
};
